// Generated by CIRCT unknown git version
module Adder(	// src/main/scala/Adder.scala:5:7
  input         clock,	// src/main/scala/Adder.scala:5:7
                reset,	// src/main/scala/Adder.scala:5:7
  input  [31:0] io_a,	// src/main/scala/Adder.scala:6:14
                io_b,	// src/main/scala/Adder.scala:6:14
  output [31:0] io_sum	// src/main/scala/Adder.scala:6:14
);

  assign io_sum = io_a + io_b;	// src/main/scala/Adder.scala:5:7, :12:18
endmodule


// ----- 8< ----- FILE "verification/layers-Adder-Verification.sv" ----- 8< -----

// Generated by CIRCT unknown git version
`ifndef layers_Adder_Verification	// src/main/scala/Adder.scala:5:7
  `define layers_Adder_Verification
`endif // not def layers_Adder_Verification

// ----- 8< ----- FILE "verification/assert/layers-Adder-Verification-Assert.sv" ----- 8< -----

// Generated by CIRCT unknown git version
`ifndef layers_Adder_Verification_Assert	// src/main/scala/Adder.scala:5:7
  `define layers_Adder_Verification_Assert
  `include "layers-Adder-Verification.sv"	// src/main/scala/Adder.scala:5:7
`endif // not def layers_Adder_Verification_Assert

// ----- 8< ----- FILE "verification/assume/layers-Adder-Verification-Assume.sv" ----- 8< -----

// Generated by CIRCT unknown git version
`ifndef layers_Adder_Verification_Assume	// src/main/scala/Adder.scala:5:7
  `define layers_Adder_Verification_Assume
  `include "layers-Adder-Verification.sv"	// src/main/scala/Adder.scala:5:7
`endif // not def layers_Adder_Verification_Assume

// ----- 8< ----- FILE "verification/cover/layers-Adder-Verification-Cover.sv" ----- 8< -----

// Generated by CIRCT unknown git version
`ifndef layers_Adder_Verification_Cover	// src/main/scala/Adder.scala:5:7
  `define layers_Adder_Verification_Cover
  `include "layers-Adder-Verification.sv"	// src/main/scala/Adder.scala:5:7
`endif // not def layers_Adder_Verification_Cover
